### ISSUE TITLE
setup missing

### ISSUE THREAD

**Issue by gxgani** [paranerd/simpledrive#1]
/setup seems to be missing.

**Comment by paranerd** [comment]
Do you have .htaccess and mod_rewrite enabled?

**Comment by gxgani** [comment]
I'm on nginx.

**Comment by paranerd** [comment]
At the moment, simpleDrive requires an apache2-server... You would have to manually add the rewrites to your nginx config.
Sorry for the inconvenience, I'm open for suggestions!

**Comment by paranerd** [comment]
I think I fixed the issue.

Use this in your nginx.conf (edit server_name and root according to your setup):

server {
    listen 80;
    server_name localhost;

```
root /var/www/html/simpledrive;

location ~ ^/(?:\.htaccess|docs|config|logs){
    deny all;
}

location ~* \.(?:css|js|woff|ico)$ {
    add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
}

location / {
    try_files $uri $uri/ @w;
}

location @w {
        rewrite ^/api/(.*)$ /php/api.php?request=$1 last;
        rewrite ^/webdav(.*)$ /php/webdav.php last;
        rewrite ^/(.*)$ /index.php?view=$1 last;
}
```

}

Let me know if that works for you.

**Comment by gxgani** [comment]
It did work, went through the setup but I got "Internal Server Error" on the homepage.

```
2016/04/21 11:14:37 [error] 12772#0: *11 FastCGI sent in stderr: "PHP message: PHP Warning:  file(../.htaccess): failed to open stream: No such file or directory in /home/user/www/php/core.class.php on line 107
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/user/www/php/core.class.php on line 110" while reading response header from upstream, client: ip.add, server: domain.xyz, request: "POST /api/core/setup HTTP/1.1", upstream: "fastcgi://unix:/var/run/ajenti-v-php-fcgi-domain-php-fcgi-0.sock:", host: "domain.xyz", referrer: "https://domain.xyz/"
2016/04/21 11:15:09 [error] 12772#0: *44 open() "/home/user/www/css/themes/color/dark.css" failed (2: No such file or directory), client: ip.add, server: domain.xyz, request: "GET /css/themes/color/dark.css HTTP/1.1", host: "domain.xyz", referrer: "https://domain.xyz/files"
2016/04/21 11:15:11 [error] 12772#0: *46 open() "/home/user/www/css/themes/fileview/gridview.css" failed (2: No such file or directory), client: ip.add, server: domain.xyz, request: "GET /css/themes/fileview/gridview.css HTTP/1.1", host: "domain.xyz", referrer: "https://domain.xyz/files"
2016/04/21 11:16:06 [error] 12772#0: *59 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: username in /home/user/www/php/user.class.php on line 70" while reading response header from upstream, client: ip.add, server: domain.xyz, request: "POST /api/users/get HTTP/1.1", upstream: "fastcgi://unix:/var/run/ajenti-v-php-fcgi-domain-php-fcgi-0.sock:", host: "domain.xyz", referrer: "https://domain.xyz/user"
2016/04/21 11:20:16 [error] 13096#0: *14 open() "/home/user/www/css/themes/color/dark.css" failed (2: No such file or directory), client: ip.add, server: domain.xyz, request: "GET /css/themes/color/dark.css HTTP/1.1", host: "domain.xyz", referrer: "https://domain.xyz/files"
```

**Comment by gxgani** [comment]
```
2016/04/21 11:26:14 [error] 13096#0: *18 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/home/username/www/docs/username): failed to open dir: No such file or directory' in /home/username/www/php/user.class.php:157
Stack trace:
#0 /home/username/www/php/user.class.php(157): RecursiveDirectoryIterator->__construct('/home/username/www/...')
#1 /home/username/www/php/file.class.php(344): User->checkQuota('username', 6)
#2 /home/username/www/php/api.php(95): File->create(Array, 'file', 'ss')
#3 {main}
  thrown in /home/username/www/php/user.class.php on line 157" while reading response header from upstream, client: ip.add, server: domain.xyz, request: "POST /api/files/create HTTP/1.1", upstream: "fastcgi://unix:/var/run/ajenti-v-php-fcgi-domain-php-fcgi-0.sock:", host: "domain.xyz", referrer: "https://domain.xyz/files"
```

**Comment by paranerd** [comment]
We're getting further ;-)

Does /home/username/www/docs/username/ exist?
Does /home/user/www/css/themes/color/dark.css exist?
Was the user successfully created in the database?

Please download the 2.10.4-zip and check if that fixes the errors.

**Comment by paranerd** [comment]
Simple fix at least for your second error-post should be to just logout and login again to properly set the access token (this issue got fixed in 2.10.4)

**Comment by gxgani** [comment]
I tried a fresh install, new database. This time no "Internal Sever" on the home page(the banner appears in the right bottom) but I get it when I upload the file. 

Secondly, settings shows 2KB post/upload size while phpinfo states 2G. 

Here's the new error log

```
2016/04/21 12:08:03 [error] 13096#0: *68 open() "/home/username/www/css/themes/color/dark.css" failed (2: No such file or directory), client: ip.add, server: domain.xyz, request: "GET /css/themes/color/dark.css HTTP/1.1", host: "domain.xyz", referrer: "https://domain.xyz/files?v=files&d=&r=null"
2016/04/21 12:08:49 [error] 13096#0: *81 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: username in /home/username/www/php/user.class.php on line 70" while reading response header from upstream, client: ip.add, server: domain.xyz, request: "POST /api/users/get HTTP/1.1", upstream: "fastcgi://unix:/var/run/ajenti-v-php-fcgi-domain.php-fcgi-0.sock:", host: "domain.xyz", referrer: "https://domain.xyz/user"
2016/04/21 12:09:33 [error] 13096#0: *96 FastCGI sent in stderr: "PHP message: PHP Warning:  phpinfo(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/username/www/info.php on line 5" while reading response header from upstream, client: ip.add, server: domain.xyz, request: "GET /info.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/ajenti-v-php-fcgi-domain.php-fcgi-0.sock:", host: "domain.xyz"
```

**Comment by gxgani** [comment]
One more thing, the missing files are in the sub directory assets but that's not what it shows in the log. It's looking for the files without the root directory "assets".

**Comment by paranerd** [comment]
Just released 2.10.5.
Should fix all those bugs ;-)
Please let me know if everything works as expected!

**Comment by gxgani** [comment]
I can't seem to upload files, it shows "Access Forbidden" for a micro second in the banner then changes to Internal Server Error.

Clicking "My Files" causes the same Internal Server Error.

Lastly, the changing theme still throws the same error on log (directory not found). 

I am unable to determine the cause of first two issue.

**Comment by paranerd** [comment]
Does creating and/or deleting a file/folder work?

Please clear the cache of your browser and restart it. Maybe some of the old old code got stuck^^

If the errors persist, please send me a new log-snippet.

**Comment by gxgani** [comment]
This is weird, logged in via private browsing. Themes worked, no more internal server error but I'm getting "Error Accessing Folder".

**Comment by paranerd** [comment]
I would assume that this is because no login-cookie is set in private mode. Try clearing cache/cookies and restarting your browser (which one is it if I may ask?)
And since themes work now, the problem was probably due to caching...

**Comment by gxgani** [comment]
Using FIrefox Beta for OSX. But I am sure, clearing cache/cookies would not be needed for safe browsing since it's a newer session every time you open a new safe browsing window.

**Comment by paranerd** [comment]
I can access the login-cookie in private mode (also Firefox), so clearing would be necessary.
Can you list/create/delete any files?

**Comment by gxgani** [comment]
I tried Chrome. Getting straight out "Error" while creating file/folder and "Error Accessing" on uploading.

```
2016/04/21 20:09:59 [error] 13683#0: *53 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/home/username/www/docs/username): failed to open dir: No such file or directory' in /home/username/www/php/user.class.php:157
Stack trace:
#0 /home/username/www/php/user.class.php(157): RecursiveDirectoryIterator->__construct('/home/username/www/...')
#1 /home/username/www/php/file.class.php(344): User->checkQuota('username', 6)
#2 /home/username/www/php/api.php(98): File->create(Array, 'file', 'sss.txt')
#3 {main}
  thrown in /home/username/www/php/user.class.php on line 157" while reading response header from upstream, client: ip.add, server: domain.xyz, request: "POST /api/files/create HTTP/1.1", upstream: "fastcgi://unix:/var/run/ajenti-v-php-fcgi-domain-php-fcgi-0.sock:", host: "domain.xyz", referrer: "https://domain.xyz/files"
2016/04/21 20:10:07 [error] 13683#0: *53 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/home/username/www/docs/username): failed to open dir: No such file or directory' in /home/username/www/php/user.class.php:157
Stack trace:
#0 /home/username/www/php/user.class.php(157): RecursiveDirectoryIterator->__construct('/home/username/www/...')
#1 /home/username/www/php/file.class.php(344): User->checkQuota('username', 8192)
#2 /home/username/www/php/api.php(98): File->create(Array, 'folder', 'sss')
#3 {main}
  thrown in /home/username/www/php/user.class.php on line 157" while reading response header from upstream, client: ip.add, server: domain.xyz, request: "POST /api/files/create HTTP/1.1", upstream: "fastcgi://unix:/var/run/ajenti-v-php-fcgi-domain-php-fcgi-0.sock:", host: "domain.xyz", referrer: "https://domain.xyz/files"
```

**Comment by paranerd** [comment]
Does /home/username/www/docs/username/ exist?

**Comment by gxgani** [comment]
![](http://i.imgur.com/R1soBEV.png)

**Comment by paranerd** [comment]
Did you run the setup / do you login with GaNi?
Did you change "GaNi" to "username" in the logs? Because if the user is indeed "username" and there is no folder called "username", that would of course cause an error^^

**Comment by gxgani** [comment]
I masked the logs (Find All/Replace)

**Comment by paranerd** [comment]
In php/file.class.php uncomment lines 344-347 and 1212-1216 to disable the quota check as that's where the error seems to occur.
If that's it, at least I've got a starting point^^

**Comment by gxgani** [comment]
Did you mean comment? If so, I tried commenting the lines, still no luck. "Error Accessing" without any nginx-error log.

**Comment by paranerd** [comment]
Yea, sure, comment - long day^^
I uploaded 2.10.6. Disabled the quota check and added logging for where I suspect the error to be.
Please update and paste the /logs/status.log.
Sadly, I can't reproduce the error on my system since I'm running on Linux and everything works as expected :disappointed:

**Comment by gxgani** [comment]
I am running nginx+php-fpm setup on a centos 6.7 server not on my macbook ;)

PS: Will get back

**Comment by paranerd** [comment]
On Arch Linux I had the problem that apache could not access a document root in the user's home directory unless the entire /home/username belonged to www-data...
May that be the problem? Do other php-sites work there?

**Comment by gxgani** [comment]
If it were the case, site wouldn't have been open at the first place. 

![](http://i.imgur.com/R4FlVhB.png)
PS: I am running owncloud as well in a similar setup all under Ajenti Control Panel.

**Comment by gxgani** [comment]
Here's status.log while creating a file.

```
abs: /home/gani/www/docs/gani | rel:
/home/gani/www/docs/gani does not exist
abs: /home/gani/www/docs/gani | rel:
/home/gani/www/docs/gani does not exist
abs: /home/gani/www/docs/gani | rel:
/home/gani/www/docs/gani does not exist
abs: /home/gani/www/docs/gani | rel:
/home/gani/www/docs/gani does not exist
```

I think it's because of case sensitivity.

**Comment by paranerd** [comment]
Okay, then there's the problem, right? You posted /home/gani/www/docs/GaNi as your docs location?!
Edit: oh, that's what you already mentioned^^

**Comment by gxgani** [comment]
Correct, it seems like my username was taken with case sensitivity but later it was not. Since homepage shows my username without case sensitivity.

**Comment by paranerd** [comment]
Can you check how it was written to database?

**Comment by paranerd** [comment]
Think I found the error. Will get back.

**Comment by gxgani** [comment]
![](http://i.imgur.com/0eOlw1t.png)

**Comment by paranerd** [comment]
Could finally reproduce your error. Missed to force lowercase in a couple of places.
Try 2.10.7, should work.
Thank you for your support!

**Comment by gxgani** [comment]
What was the workaround? My name is still in lowercase (not interpreted as-is from db). Secondly, I still get Internal Server Error on uploading files. (Can create files and folders)
While uploading, I noticed the file does get uploaded to server(process complete) but ends with the error.,

**Comment by gxgani** [comment]
```
2016/04/22 08:15:53 [error] 14221#0: *216 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: username in /home/gani/www/php/user.class.php on line 71" while reading response header from upstream, client: ip.add, server: domain.xyz, request: "POST /api/users/get HTTP/1.1", upstream: "fastcgi://unix:/var/run/ajenti-v-php-fcgi-domain-php-fcgi-0.sock:", host: "domain.xyz", referrer: "https://domain.xyz/user"
2016/04/22 08:17:56 [error] 14221#0: *255 client intended to send too large body: 6884090 bytes, client: ip.add, server: domain.xyz, request: "POST /api/files/upload HTTP/1.1", host: "domain.xyz", referrer: "https://domain.xyz/files?v=files&d=&r=null"
```

**Comment by paranerd** [comment]
You would either need to re-run the setup or change your username in database and the foldername to lowercase (all usernames must be lowercase) --> this will fix the "undefined index" error (I will get some better error handling in there!)

To fix that upload error I had to add
client_max_body_size 20M (or any other value of your choice)
into the server{]-part of your nginx.conf

Since nginx-support is relatively new, you would need to do that manually as the settings-page only updates the .htaccess

**Comment by gxgani** [comment]
Changed the username, logged in. Now uploading a file just shows an "Error Banner".

**Comment by paranerd** [comment]
Did you change the folder to lowercase as well?
Any error-logs?

**Comment by gxgani** [comment]
yes and no(nginx and logs directory)

**Comment by paranerd** [comment]
Does the error only appear on uploading or on creating as well?

**Comment by gxgani** [comment]
uploading only. Creating and editing a text file worked.

**Comment by paranerd** [comment]
So we're making progress here xD
I added some status messages in the upload-function for 2.10.9 to narrow down on the error.
Please update, re-try and paste the /logs/status.log.

**Comment by gxgani** [comment]
weird, very weird.
Status log

```
upload_max_filesize raw: 2G
upload_max_filesize int: 0
file too big
```

But..
![](http://i.imgur.com/ARjXi77.png)

**Comment by paranerd** [comment]
Seems to be something wrong with the parsing :disappointed: 
If you comment lines 1200 - 1205 (disable size check) in /php/file.class.php, does it work?

**Comment by paranerd** [comment]
Are you running a 32bit-System?

**Comment by paranerd** [comment]
Error found and fixed.
2G is too large for int^^
